# Convertion of FEMTO dataset to CMAPSS-like dataset

To transfer CMAPSS model to the FEMTO dataset, a simple convertion is applied on the original FEMTO datasets with the following step : each segment is compressed into 16 fetatures each, representating 8 statistical time-domain features and 8 statistical frequency-domain features using fast fourier transform. The statistical features are (for time and frequency) : mean, std, RMS, kurtosis, max of abs, min of abs, skewness, peak-to-peak.

In [1]:
%reset -f

In [ ]:
import sys
sys.path.append('../')
import pyrul
import pandas as pd
import numpy as np
from pyrul.utils.compat import convert_femto_to_cmapss

2025-07-29 10:45:03.413622: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-29 10:45:03.471602: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-07-29 10:45:05.866430: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Importing the dtw module. When using in academic works please cite:
  T. Giorgino. Computing and Visualizing Dynamic Time Warping Alignments in R: The dtw Package.
  J. Stat. Soft., doi:10.18637/jss.v031.i07.

In [ ]:
femto_train_data_path = "../datasets/femto/training_data.csv"
femto_test_data_path = "../datasets/femto/test_data.csv"

In [4]:
df_train = pd.read_csv(femto_train_data_path, sep=",")
df_test = pd.read_csv(femto_test_data_path, sep=",")

In [5]:
df_train.head()

   hori_acc  vert_acc    RUL  unit  condition
0     0.552    -0.146  28020     1          1
1     0.501    -0.480  28020     1          1
2     0.138     0.435  28020     1          1
3    -0.423     0.240  28020     1          1
4    -0.802     0.020  28020     1          1

In [6]:
df_train_new = convert_femto_to_cmapss(df_train)
df_test_new = convert_femto_to_cmapss(df_test)

In [7]:
df_train_new.head()

,hori_acc_f0,vert_acc_f0,hori_acc_f1,vert_acc_f1,hori_acc_f2,vert_acc_f2,hori_acc_f3,vert_acc_f3,hori_acc_f4,vert_acc_f4,...,vert_acc_f12,hori_acc_f13,vert_acc_f13,hori_acc_f14,vert_acc_f14,hori_acc_f15,vert_acc_f15,RUL,unit,condition
0,0.003465,-0.001881,0.561735,0.435797,0.561746,0.435801,2.868535,2.964920,2.010,1.591,...,83.899497,0.177479,0.310128,3.936500,1.382314,289.715729,83.589369,28020,1,1
1,0.005609,-0.000930,0.535083,0.420967,0.535112,0.420968,2.915354,3.150620,1.915,1.666,...,75.805603,0.081624,0.067718,2.795432,1.300133,168.316715,75.737886,28010,1,1
2,0.004196,-0.002229,0.531142,0.425600,0.531158,0.425605,3.033388,2.938448,1.901,1.584,...,101.198008,0.097486,0.030304,3.342024,1.581403,202.293495,101.167704,28000,1,1
3,-0.001824,-0.000594,0.554830,0.445524,0.554833,0.445524,3.043419,2.886681,1.910,1.600,...,83.486037,0.250214,0.352470,3.707330,1.314672,244.989945,83.133566,27990,1,1
4,-0.002582,0.009918,0.566646,0.423731,0.566652,0.423847,2.814523,2.965184,1.767,1.373,...,78.275896,0.261027,0.531731,3.661169,1.229671,236.768850,77.744165,27980,1,1

In [8]:
# Verification : hori_acc RMS of unit 3's segment with RUL set to 20, should be equal in both datasets

In [9]:
np.mean(np.square(df_train[(df_train.unit==3) & (df_train.RUL==20)]["hori_acc"]))**0.5

2.2080374478467863

In [10]:
df_train_new[df_train_new.unit==3]["hori_acc_f2"].iloc[-3]

2.2080374478467855

In [ ]:
# Saving datasets
df_train_new.to_csv("./training_data.csv", sep=",")
df_test_new.to_csv("./test_data.csv", sep=",")